version: "3.9"

networks:
  printscript-net:
    name: printscript-net

volumes:
  pg_snippets: {}
  pg_tests: {}

services:
  pg-snippets:
    image: postgres:16
    environment:
      POSTGRES_USER: ${SNIPPETS_DB_USER}
      POSTGRES_PASSWORD: ${SNIPPETS_DB_PASS}
      POSTGRES_DB: snippets
    volumes:
      - pg_snippets:/var/lib/postgresql/data
    networks: [printscript-net]

  pg-tests:
    image: postgres:16
    environment:
      POSTGRES_USER: ${TESTS_DB_USER}
      POSTGRES_PASSWORD: ${TESTS_DB_PASS}
      POSTGRES_DB: tests
    volumes:
      - pg_tests:/var/lib/postgresql/data
    networks: [printscript-net]

  execution:
    image: ${EXECUTION_IMAGE}:${EXECUTION_TAG}
    container_name: ps-execution
    environment:
      LOGGING_LEVEL_ROOT: INFO
    networks: [printscript-net]

  snippets:
    image: ${SNIPPETS_IMAGE}:${SNIPPETS_TAG}
    container_name: ps-snippets
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg-snippets:5432/snippets
      SPRING_DATASOURCE_USERNAME: ${SNIPPETS_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SNIPPETS_DB_PASS}
      EXECUTION_BASE_URL: http://execution:8082
      LOGGING_LEVEL_ROOT: INFO
    depends_on: [ pg-snippets, execution ]
    networks: [printscript-net]

  tests:
    image: ${TESTS_IMAGE}:${TESTS_TAG}
    container_name: ps-tests
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg-tests:5432/tests
      SPRING_DATASOURCE_USERNAME: ${TESTS_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${TESTS_DB_PASS}
      EXECUTION_BASE_URL: http://execution:8082
      LOGGING_LEVEL_ROOT: INFO
    depends_on: [ pg-tests, execution ]
    networks: [printscript-net]