events {}

http {
   proxy_set_header Host              $host;
   proxy_set_header X-Real-IP         $remote_addr;
   proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;

  # Tiempos de espera
  proxy_connect_timeout   5s;
  proxy_send_timeout      60s;
  proxy_read_timeout      60s;
  send_timeout            60s;

  upstream printscript_ui_upstream { server printscript-ui:80; }
  upstream authorization_upstream { server authorization:8080; }
  upstream execution_upstream     { server execution:8080; }
  upstream snippets_upstream      { server snippets:8080; }
  upstream certbot_upstream       { server certbot:80; }

  server {
    listen 80;
    listen 443 ssl;

    # Dominio y certificados (DEV por defecto)
    server_name printscript-dev.duckdns.org;

    # Rutas SSL
    ssl_certificate /etc/letsencrypt/live/printscript-dev.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/printscript-dev.duckdns.org/privkey.pem;

    # Redireccion HTTP a HTTPS
    if ($scheme = http) {
        return 301 https://$host$request_uri;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # /api/snippets/ -> snippets
    location /api/snippets/ {
      rewrite ^/api/snippets/(.*)$ /$1 break;
      proxy_pass http://snippets_upstream;
    }

    # /api/authorization/ -> authorization
    location /api/authorization/ {
      rewrite ^/api/authorization/(.*)$ /$1 break;
      proxy_pass http://authorization_upstream;
    }

    # /api/execution/ -> execution
    location /api/execution/ {
      rewrite ^/api/execution/(.*)$ /$1 break;
      proxy_pass http://execution_upstream;
    }

    location / {
      try_files $uri $uri/ @ui_fallback;
    }

    location @ui_fallback {
      proxy_pass http://printscript_ui_upstream;
      rewrite ^.*$ /index.html break;
    }
  }
}