events {}

http {
   # Origins permitidos
   map $http_origin $cors_allow_origin {
       default "";
       "http://localhost:5173" "http://localhost:5173";
       "https://printscript-dev.duckdns.org" "https://printscript-dev.duckdns.org";
       "https://printscript-prod.duckdns.org" "https://printscript-prod.duckdns.org";
   }

   proxy_set_header Host              $host;
   proxy_set_header X-Real-IP         $remote_addr;
   proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;

   proxy_set_header Authorization $http_authorization;
   proxy_pass_header Authorization; # Propaga el token JWT del usuario

  # Tiempos de esperaa
  proxy_connect_timeout   5s;
  proxy_send_timeout      60s;
  proxy_read_timeout      60s;
  send_timeout            60s;

  upstream printscript_ui_upstream { server printscript-ui:80; }
  upstream authorization_upstream { server authorization:8080; }
  upstream execution_upstream     { server execution:8080; }
  upstream snippets_upstream      { server snippets:8080; }
  upstream certbot_upstream       { server certbot:80; }

  server {
    listen 80;
    listen 443 ssl;

    # Dominio y certificados (DEV por defecto)
    server_name printscript-dev.duckdns.org;

    # Rutas SSL
    ssl_certificate /etc/letsencrypt/live/printscript-dev.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/printscript-dev.duckdns.org/privkey.pem;

    # Redireccion HTTP a HTTPS
    if ($scheme = http) {
        return 301 https://$host$request_uri;
    }

    # CORS PREFLIGHT CHECK (Manejo de OPTIONS)
    if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '$cors_allow_origin';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Authorization, DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Max-Age' 2592000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
    }

    # excepcion para certbot para renovar certif
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # /api/snippets/ -> snippets
    location /api/snippets/ {
      add_header 'Access-Control-Allow-Origin' '$cors_allow_origin';
      rewrite ^/api/snippets/(.*)$ /$1 break;
      proxy_pass http://snippets_upstream;
    }

    # /api/authorization/ -> authorization
    location /api/authorization/ {
      add_header 'Access-Control-Allow-Origin' '$cors_allow_origin';
      rewrite ^/api/authorization/(.*)$ /$1 break;
      proxy_pass http://authorization_upstream;
    }

    # /api/execution/ -> execution
    location /api/execution/ {
      add_header 'Access-Control-Allow-Origin' '$cors_allow_origin';
      rewrite ^/api/execution/(.*)$ /$1 break;
      proxy_pass http://execution_upstream;
    }

    location / {
      try_files $uri $uri/ @ui_fallback;
    }

    location @ui_fallback {
      proxy_pass http://printscript_ui_upstream;
      rewrite ^.*$ /index.html break;
    }
  }
}